# Generated by Django 6.1.1 on 2026-09-08 07:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label_it', models.CharField(max_length=64)),
                ('default_bar_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('load_increment_kg', models.DecimalField(decimal_places=2, default=2.5, help_text="Il passo minimo con cui su questo attrezzo il carico può salire davvero. Zero sul corpo libero e sull'elastico: lì il coach consiglia ripetizioni, mai carico — è la regola, non un dato mancante.", max_digits=4, verbose_name='incremento minimo di carico (kg)')),
                ('sort_order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'attrezzo',
                'verbose_name_plural': 'attrezzi',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label_it', models.CharField(max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'muscolo',
                'verbose_name_plural': 'muscoli',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('label_it', models.CharField(max_length=64)),
                ('sort_order', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'gruppo muscolare',
                'verbose_name_plural': 'gruppi muscolari',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('body_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Un solo valore corrente, non uno storico.', max_digits=5, null=True, verbose_name='peso corporeo (kg)')),
                ('is_synthetic', models.BooleanField(default=False, help_text='Generato da seed_synthetic; va dichiarato in interfaccia.', verbose_name='utente sintetico')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utente',
                'verbose_name_plural': 'utenti',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(help_text='Generato da load_catalog, non a runtime: gli URL devono essere stabili.', max_length=140, unique=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='training.equipment')),
                ('primary_muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='training.muscle')),
            ],
            options={
                'verbose_name': 'esercizio',
                'verbose_name_plural': 'esercizi',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='muscle',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='muscles', to='training.musclegroup'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('is_public', models.BooleanField(default=False, help_text='Solo una scheda pubblica è visibile e votabile dagli altri.', verbose_name='pubblica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'scheda',
                'verbose_name_plural': 'schede',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(verbose_name='posizione')),
                ('target_sets', models.PositiveSmallIntegerField(verbose_name='serie previste')),
                ('target_reps', models.PositiveSmallIntegerField(help_text='Estremo basso del range.', verbose_name='ripetizioni minime')),
                ('target_reps_max', models.PositiveSmallIntegerField(blank=True, help_text='Estremo alto: è questo che la doppia progressione insegue.', null=True, verbose_name='ripetizioni massime')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.routine')),
            ],
            options={
                'verbose_name': 'esercizio della scheda',
                'verbose_name_plural': 'esercizi della scheda',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='voto')),
                ('comment', models.TextField(blank=True, verbose_name='commento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='training.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'voti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Istantanea del nome della scheda al momento dell'esecuzione.", max_length=120, verbose_name='titolo')),
                ('started_at', models.DateTimeField(verbose_name='iniziato il')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='finito il')),
                ('notes', models.TextField(blank=True, verbose_name='note')),
                ('external_id', models.UUIDField(blank=True, help_text="Idempotenza dell'import. Nullo per gli allenamenti nati in-app.", null=True, unique=True)),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to='training.routine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'allenamento',
                'verbose_name_plural': 'allenamenti',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveSmallIntegerField(verbose_name='numero di serie')),
                ('reps', models.PositiveSmallIntegerField(blank=True, help_text='Nullo se la serie è stata saltata.', null=True, verbose_name='ripetizioni')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Nullo se saltata. Zero è legittimo sul corpo libero.', max_digits=6, null=True, verbose_name='carico (kg)')),
                ('set_type', models.CharField(choices=[('working', 'Efficace'), ('warmup', 'Riscaldamento'), ('rampUp', 'Avvicinamento')], default='working', max_length=16, verbose_name='tipo di serie')),
                ('is_completed', models.BooleanField(default=True, verbose_name='eseguita')),
                ('external_id', models.UUIDField(blank=True, help_text="Idempotenza dell'import.", null=True, unique=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.workout')),
            ],
            options={
                'verbose_name': 'serie',
                'verbose_name_plural': 'serie',
                'ordering': ['set_number'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=160, verbose_name='nome grezzo')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alias di esercizio',
                'verbose_name_plural': 'alias di esercizio',
                'ordering': ['raw_name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'raw_name'), name='exercise_alias_unique_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='exercise',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='exercise_name_unique_ci'),
        ),
        migrations.AddConstraint(
            model_name='routineexercise',
            constraint=models.UniqueConstraint(fields=('routine', 'exercise'), name='routine_exercise_unique'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'routine'), name='vote_unique_per_user_routine'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='vote_score_between_1_and_5'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', '-started_at'], name='workout_user_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='workout',
            constraint=models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='workout_ended_after_started'),
        ),
        migrations.AddIndex(
            model_name='workoutset',
            index=models.Index(fields=['exercise'], name='workout_set_exercise_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.UniqueConstraint(fields=('workout', 'exercise', 'set_number'), name='workout_set_unique'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('is_completed', False), ('reps__gt', 0), _connector='OR'), name='workout_set_completed_has_reps'),
        ),
        migrations.AddConstraint(
            model_name='workoutset',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gte', 0), _connector='OR'), name='workout_set_weight_non_negative'),
        ),
    ]
